### ISSUE TITLE
Running eval_all.m , use cpu can get correct result, but GPU got a wrong result

### ISSUE THREAD

**Issue by Hutai** [hszhao/PSPNet#31]
Why I use cpu to run the eval_all.m got correct pictures of prediction, but using gpu can not get what I want that it output whole black or whole yellow images?

**Comment by Hutai** [comment]
I have solved this problem, it is cudnn version of the problem, change to other versions of cudnn or uncomment cudnn configuration information

**Comment by balloch** [comment]
safest bet might just be to run without cuDNN if this is the case. only accounts for about a 40% speedup on eval and a 35% speedup on training
